version: '2'
services:

    web:
        build: ./
        volumes:
            - ./:/var/www/html/
            - ~/.composer/cache:/root/.composer/cache
            - ~/.ssh:/root/.ssh
            - ./services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
            API_TOKEN: "47591fb1175145933b20f80d89c9da0381e9339a"
        expose:
            - 9000

    nginx:
        build: ./services/nginx
        ports:
            - "80:80"
        links:
            - web
        volumes_from:
            - web

    db:
        image: mysql:5.6
        ports:
            - "3316:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web
        volumes:
            - ./services/mysql:/var/lib/mysql
            - ./services/mysql/mysql.cfg:/etc/mysql/conf.d/mysql.cfg
        # Autostart at boottime
        #restart: always
