version: '2'
services:

    web:
        container_name: yii2-app-advanced
        image: registry.domain.com/namespace/yii2-app-advanced:latest
        volumes:
            - ./.env:/var/www/html/.env
            - ./data/api/runtime:/var/www/html/api/runtime
            - ./data/api/web/assets:/var/www/html/api/web/assets
            - ./data/backend/runtime:/var/www/html/backend/runtime
            - ./data/backend/web/assets:/var/www/html/backend/web/assets
            - ./data/console/runtime:/var/www/html/console/runtime
            - ./data/frontend/runtime:/var/www/html/frontend/runtime
            - ./data/frontend/web/assets:/var/www/html/frontend/web/assets
            - ./data/frontend/web/uploads:/var/www/html/frontend/web/uploads
        links:
            - mysql
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
            API_TOKEN: "47591fb1175145933b20f80d89c9da0381e9339a"
        expose:
            - 9000

    nginx:
        build: ./services/nginx
        ports:
            - "999:999"
        links:
            - web
        volumes_from:
            - web

    mysql:
        image: mysql:5.6
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./services/mysql/mysql.cfg:/etc/mysql/conf.d/mysql.cfg